// Generated by LiveScript 1.3.1
(function(){
  var React, api, Header, Dom, div, PersonDetail;
  React = require('react');
  api = require('../../api/api');
  Header = require('../../components/Header');
  Dom = React.DOM;
  div = Dom.div;
  PersonDetail = React.createClass({
    displayName: "PersonDetail",
    getInitialState: function(){
      return {
        person: {}
      };
    },
    componentWillMount: function(){
      var this$ = this;
      return api.person.get(this.props.params.resourceId).then(function(it){
        return this$.setState({
          person: it
        });
      });
    },
    title: function(it){
      switch (false) {
      case !it.middleName:
        return it.firstName + " " + it.middleName + " " + it.lastName;
      case !it.firstName:
        return it.firstName + " " + it.lastName;
      default:
        return "Loading...";
      }
    },
    render: function(){
      return div(null, Header({
        title: this.title(this.state.person)
      }), div({
        className: "main container"
      }, "Detail page!"));
    }
  });
  module.exports = PersonDetail;
}).call(this);
