'use strict';

var keyMirror = require('react/lib/keyMirror');

module.exports = keyMirror({
  SHOW_NOTIFICATION: null,
  HIDE_NOTIFICATION: null,

  SHOW_ALERT: null,
  HIDE_ALERT: null,

  SHOW_MODAL: null,
  HIDE_MODAL: null,

  SHOW_SIDEBAR: null,
  HIDE_SIDEBAR: null,

  SHOW_CONTEXT_MENU: null,
  HIDE_CONTEXT_MENU: null,

  SHOW_PAGE_CONTROLS: null,
  HIDE_PAGE_CONTROLS: null,


  SHOW_FORM_MESSAGES: null,
  HIDE_FORM_MESSAGES: null,

  FORM_VALUE_CHANGED: null,

  SUBMIT_FORM: null,
  SUBMIT_FORM_SUCCESS: null,
  SUBMIT_FORM_ERROR: null,

  RESET_FORM: null,

  SAVE_SETTINGS: null,
  SAVE_SETTINGS_SUCCESS: null,
  SAVE_SETTINGS_ERROR: null,

  REQUEST_RESET_PASSWORD: null,
  REQUEST_RESET_PASSWORD_SUCCESS: null,
  REQUEST_RESET_PASSWORD_ERROR: null,

  RESET_PASSWORD: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_ERROR: null,

  REQUEST_EDITOR_INVITE: null,
  REQUEST_EDITOR_INVITE_SUCCESS: null,
  REQUEST_EDITOR_INVITE_FAILURE: null,

  SIGNOUT: null,
  SPECIFY_LOGIN_OPTIONS: null,

  LOGIN_WITH_EMAIL: null,
  LOGIN_WITH_EMAIL_SUCCESS: null,
  LOGIN_WITH_EMAIL_ERROR: null,

  RESEND_UNCONFIRMED_EMAIL: null,
  RESEND_UNCONFIRMED_EMAIL_SUCCESS: null,
  RESEND_UNCONFIRMED_EMAIL_ERROR: null,

  CANCEL_UNCONFIRMED_EMAIL: null,
  CANCEL_UNCONFIRMED_EMAIL_SUCCESS: null,
  CANCEL_UNCONFIRMED_EMAIL_ERROR: null,

  ENTER_LIGHTBOX: null,
  LEAVE_LIGHTBOX: null,

  RESIZE_WINDOW: null,
});


/** WEBPACK FOOTER **
 ** ./constants/ActionTypes.js
 **/
