// Generated by LiveScript 1.3.1
(function(){
  var React, Link, ModalMixin, FormMixin, AutocompleteFor, Modal, api, Dom, div, button, form, label, CreateClassModal;
  React = require('react');
  Link = require('react-router').Link;
  ModalMixin = require('../../components/ModalMixin');
  FormMixin = require('../../components/FormMixin');
  AutocompleteFor = require('../../components/AutocompleteFor');
  Modal = require('../../components/SemanticModal');
  api = require('../../api/api');
  Dom = React.DOM;
  div = Dom.div, button = Dom.button, form = Dom.form, label = Dom.label;
  CreateClassModal = React.createClass({
    mixins: [FormMixin('class')],
    displayName: "CreateClassModal",
    handleSubmit(){
      var this$ = this;
      api['class'].create(this.state['class']).then(function(){
        return this$.props.onRequestHide();
      }).error(function(it){
        return this$.setState({
          errors: it.body
        });
      });
    },
    getInitialState(){
      return {
        'class': {},
        errors: null
      };
    },
    render(){
      return this.transferPropsTo(Modal.SemanticModal({
        title: "Create Class",
        animation: true
      }, div({
        className: "content"
      }, form({
        className: "ui form",
        onSubmit: this.handleSubmit
      }, this.messages({
        messages: this.state.errors
      }), this.inputFor('name', {
        label: 'Name'
      }), div({
        className: "ui two fields"
      }, this.inputFor('maxStudents', {
        label: 'Max Students'
      }), div({
        className: "field"
      }, label(null, "Grade Level"), this.updatableFor(AutocompleteFor.GradeLevel, 'gradeLevel', null))), div({
        className: "field"
      }, label(null, "Term"), this.updatableFor(AutocompleteFor.SchoolTerms, 'term', null)), this.actions({
        onSubmit: this.handleSubmit,
        onCancel: this.props.onRequestHide
      })))));
    }
  });
  module.exports = CreateClassModal;
}).call(this);
