// Generated by LiveScript 1.3.1
(function(){
  var React, Panel, Dom, div, form, input, label, select, ClassSettings;
  React = require('react');
  Panel = require('../../components/Panel.ls');
  Dom = React.DOM;
  div = Dom.div, form = Dom.form, input = Dom.input, label = Dom.label, select = Dom.select;
  ClassSettings = React.createClass({
    displayName: "ClassSettings",
    getInitialState: function(){
      return {
        settings: this.props['class']
      };
    },
    handleChange: function(key, val){
      this.state.settings[key] = val;
      return this.setState({
        settings: this.state.settings
      });
    },
    submit: function(){
      return console.log("a");
    },
    render: function(){
      return div(null, div({
        className: "ui form segment"
      }, div({
        className: "ui submit button",
        onClick: this.submit
      }, "Save")));
    }
  });
  module.exports = ClassSettings;
}).call(this);
