// Generated by LiveScript 1.3.1
(function(){
  var React, ref$, Router, Navigation, Panel, auth, Dom, form, div, span, i, input, button, h2, li, ul, h4, img, LoginPage, LoginLoading;
  React = require('react');
  ref$ = require('react-router'), Router = ref$.Router, Navigation = ref$.Navigation;
  Panel = require('../components/Panel');
  auth = require('../api/auth');
  Dom = React.DOM;
  form = Dom.form, div = Dom.div, span = Dom.span, i = Dom.i, input = Dom.input, button = Dom.button, h2 = Dom.h2, li = Dom.li, ul = Dom.ul, h4 = Dom.h4, img = Dom.img;
  LoginPage = React.createClass({
    displayName: "LoginPage",
    mixins: [Navigation],
    getInitialState: function(){
      return {
        error: null,
        isLoggingIn: false
      };
    },
    handleSubmit: function(e){
      var email, password, this$ = this;
      e.preventDefault();
      this.setState({
        isLoggingIn: true
      });
      email = this.refs.email.getDOMNode().value.trim();
      password = this.refs.password.getDOMNode().value.trim();
      auth.login({
        email: email,
        password: password
      }).then(function(){
        return this$.transitionTo('dashboard');
      }).error(function(it){
        return this$.setState({
          isLoggingIn: false,
          error: it
        });
      });
    },
    renderMessages: function(){
      if (this.state.error !== null) {
        return div({
          className: "ui error visible message"
        }, this.state.error.statusCode + ": " + this.state.error.message);
      }
    },
    render: function(){
      return div({
        className: "login container"
      }, img({
        className: "logo",
        src: "logo.svg"
      }), div(null, form({
        className: "ui fluid form segment",
        onSubmit: this.handleSubmit
      }, h4({
        className: "ui header"
      }, "Login"), this.renderMessages(), div({
        className: "field"
      }, div({
        className: "ui right labeled left icon input"
      }, input({
        type: "email",
        placeholder: "Email Address",
        ref: "email",
        required: true
      }), i({
        className: "user icon"
      }), div({
        className: "ui corner label"
      }, i({
        className: "icon asterisk"
      })))), div({
        className: "field"
      }, div({
        className: "ui right labeled left icon input"
      }, input({
        type: "password",
        placeholder: "Password",
        ref: "password",
        required: true
      }), i({
        className: "lock icon"
      }), div({
        className: "ui corner label"
      }, i({
        className: "icon asterisk"
      })))), div({
        className: "field"
      }, button({
        type: "submit",
        disabled: this.state.isLoggingIn,
        role: "button",
        className: "ui primary fluid submit button",
        value: "Post"
      }, LoginLoading({
        isLoggingIn: this.state.isLoggingIn
      }), "Log in")))));
    }
  });
  LoginLoading = React.createClass({
    displayName: "LoginLoading",
    render: function(){
      var style;
      style = {};
      if (!this.props.isLoggingIn === true) {
        style.display = "none";
      }
      return i({
        className: "fa fa-cog fa-spin",
        style: style
      });
    }
  });
  module.exports = LoginPage;
}).call(this);
