// Generated by LiveScript 1.3.1
(function(){
  var React, Header, api, Dom, form, div, span, i, input, button, label, Settings;
  React = require('react');
  Header = require('../components/PageHeader');
  api = require('../api/api');
  Dom = React.DOM;
  form = Dom.form, div = Dom.div, span = Dom.span, i = Dom.i, input = Dom.input, button = Dom.button, label = Dom.label;
  Settings = React.createClass({
    displayName: "SchoolSettings",
    handleSubmit: function(e){
      e.preventDefault();
    },
    handleChange: function(e, key){
      var ref$;
      return this.setState((ref$ = {}, ref$[key + ""] = e.target.value, ref$));
    },
    render: function(){
      return div(null, Header({
        primary: "School / Settings"
      }), div({
        className: "main container"
      }, div({
        className: "ui form segment"
      }, div({
        className: "actions"
      }, div({
        className: "ui submit button"
      }, "Save")))));
    }
  });
  module.exports = {
    Settings: Settings
  };
}).call(this);
