// Generated by LiveScript 1.3.1

var React, api, Header, Dom, div, PersonDetail;
React = require("react");
api = require("../../api/api");
// Header = require('../../components/Header');
Dom = React.DOM;
div = Dom.div;
PersonDetail = React.createClass({
  displayName: "PersonDetail",
  getInitialState() {
    return {
      person: {}
    };
  },
  componentWillMount() {
    var this$ = this;
    return api.person.get(this.props.match.params.id).then(function(it) {
      return this$.setState({
        person: it
      });
    });
  },
  title: function(it) {
    switch (false) {
      case !it.middleName:
        return it.firstName + " " + it.middleName + " " + it.lastName;
      case !it.firstName:
        return it.firstName + " " + it.lastName;
      default:
        return "Loading...";
    }
  },
  render() {
    return div(
      null,
      Header({
        title: this.title(this.state.person)
      }),
      div(
        {
          className: "main container"
        },
        "Detail page!"
      )
    );
  }
});
module.exports = PersonDetail;
