// Generated by LiveScript 1.3.1
(function(){
  var React, Link, index, Dom, div;
  React = require('react');
  Link = require('react-router').Link;
  index = require('../utils/index');
  Dom = React.DOM;
  div = Dom.div;
  module.exports = function(){
    return {
      getInitialState(){
        return {
          isSaving: false,
          error: null
        };
      },
      modalSaving(){
        this.setState({
          isSaving: true
        });
      },
      modalSaveSuccess(){
        this.props.onRequestHide();
      },
      modalSaveFail: function(error){
        if (this.state.isSaving) {
          this.setState({
            isSaving: false,
            error: error.errors
          });
        }
      },
      errorAlerts(){
        if (this.state.error) {
          return div({
            bsStyle: "danger"
          }, this.state.error);
        }
      }
    };
  };
}).call(this);
