var constants = {
  LOAD_BUZZ: "LOAD_BUZZ",
  LOAD_BUZZ_SUCCESS: "LOAD_BUZZ_SUCCESS",
  LOAD_BUZZ_FAIL: "LOAD_BUZZ_FAIL",

  ADD_BUZZ: "ADD_BUZZ",
  ADD_BUZZ_SUCCESS: "ADD_BUZZ_SUCCESS",
  ADD_BUZZ_FAIL: "ADD_BUZZ_FAIL"
};



actions =
  
