// Generated by LiveScript 1.2.0
(function(){
  var api;
  require('LiveScript');
  api = require('./api');
  api.baseUrl = 'http://localhost:5005/api';
  console.log("Logging in");
  api.session.create({
    email: "test@test.com",
    password: "somePassword"
  }).then(function(it){
    return console.log(it != null ? it.body : void 8);
  }).then(function(it){
    return console.log(JSON.stringify(it, null, 4));
  })['catch'](function(err){
    var x, key, val;
    x = {};
    for (key in err) {
      val = err[key];
      if (typeof val !== 'object') {
        x[key] = val;
      }
    }
    return console.log(x);
  });
  /*
  setTimeout getPerson, 500
  
  getPerson = ->
    api.person.find!
      .then ->
          console.log JSON.stringify it, null, 4
      .catch (err) ->
          x = {}
          for key, val of err
              x[key] = val unless typeof val is 'object'
          console.log x*/
}).call(this);
