// Generated by LiveScript 1.3.1
(function(){
  var React, Dom, div, h4, PanelBody, Panel;
  React = require('react');
  Dom = React.DOM;
  div = Dom.div, h4 = Dom.h4;
  PanelBody = React.createClass({
    displayName: "PanelBody",
    render(){
      return div({
        className: "ui segment attached"
      }, this.props.children);
    }
  });
  Panel = React.createClass({
    displayName: "Panel",
    render(){
      return this.transferPropsTo(div(null, h4({
        className: "ui top header attached"
      }, this.props.title), this.props.hasBody
        ? PanelBody(null, this.props.children)
        : this.props.children));
    }
  });
  module.exports = Panel;
}).call(this);
